version: "3.9"

services:
    client:
        container_name: rpgmanager-client
        restart: unless-stopped
        build:
            context: ./
        ports:
            - 3000:3000
        command: >
            sh -c "yarn run dev"
        volumes:
            - /usr/app/node_modules
            - ./react-app:/usr/app
        environment:
            - CHOKIDAR_USEPOLLING=true
